### ISSUE TITLE
ObjectStoreFileSystem caches credentials, endpoints

### ISSUE THREAD

**Issue by tsnee** [CODAIT/stocator#203]
My reading of stocator/src/main/java/com/ibm/stocator/fs/ObjectStoreFileSystem.java is that its _initialize_ method only instantiates an IStoreClient the first time it is called. If _initialize_ is called a second time with a different endpoint and credentials, those settings are ignored.

This caused a problem for me during development because I needed to try several calls before I found the right parameters. I think it poses a potential production problem for my multi-tenant project. If two clients end up using the same fsuri (say **cos://test-bucket.cloud-object-storage/**) then the second client will get access to the first client's files.

**Comment by gilv** [comment]
@tsnee This is not something that was invented in Stocator, but used by Hadoop eco-system, for example in hadoop-openstack project. The idea that you may have different endpoints and object storage instances, local, cloud, etc.
About initialize - Spark caches connectors on init. As Stocator was developed mainly for Spark the behavior of one time init - is exactly what is needed, otherwise it will initiated by Spark every time.

About security issues - you are not suppose to have tenants on the same Spark instance. Each should have it's own instance. Each client has it's own instance, otherwise each client can access data of another client. This security issue is not related Stocator, but the way you build multi tenant environment with Spark
