### ISSUE TITLE
Seems like stocator caches the previous failed read object status

### ISSUE THREAD

**Issue by dkazakevich** [CODAIT/stocator#206]
Sometimes in process of writing data into COS using Stocator, Spark job could down and we have a broken COS object (created only empty object without _SUCCESS and data parts) and on the following step reading this object throw the "_org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually_" exception. 
We also have this object backup. So in process of this object reading if get the "_AnalysisException_" exception, we restore this object (read backup and write into the main object) and trying to read this object again, but getting the same exception despite this object is valid in the COS. Only another job/run can read this object correctly. Seems like Stocator caches the previous failed read object status in the session scope.

**Comment by gilv** [comment]
@dkazakevich interesting...in general this violate the way Spark suppose to work. If you use Spark to access object 'foo' then it's not supposed to be modified in object storage, since Spark already created DAG and all is cached. 
But i understand your flow... I wonder if the right way to resolve this is to delete on failure flag to be true...this way, you use Spark to access broken object, no _SUCCESS, Stocator suppose to delete broken objecy when this flag is true, and then you re-create it and nothing in cache.

I need to test it that it works like this, but i also want to review the cache flow of _SUCCESS and perhas remove the cache anyway so it will fix the issue you observed. 
Thanks for reporting this.

**Comment by dkazakevich** [comment]
Hi @gilv 
Did you have a chance to review the issue?

**Comment by gilv** [comment]
@dkazakevich i need to recall the issue. It was reported a year ago..so the problem is that you use Spark to access object "abc" and it's broken..then some process outside of Spark restore object "abc" and you want to use same Spark context to read "abc" again?

**Comment by dkazakevich** [comment]
@gilv The issue was resolved by `spark.sql.parquet.cacheMetadata=false`.
