### ISSUE TITLE
Stocator maven releases are out of date

### ISSUE THREAD

**Issue by IainMeeke** [CODAIT/stocator#240]
I am using maven to include the stocator library in my project. I have taken the jar from the maven repository here https://mvnrepository.com/artifact/com.ibm.stocator/stocator/1.0.37.

While using the jar I have been getting the error `com.ibm.stocator.fs.common.exception.ConfigurationParseException: Configuration parse exception: Access KEY is empty. Please provide valid access key`.

From my understanding of the documentation I must provide either an access key or an api key. I have chosen to provide the API key. This understanding is supported by the code in branch 1.0.37 for the COSAPIClient in the code [here](https://github.com/CODAIT/stocator/blob/1.0.37-ibm-sdk/src/main/java/com/ibm/stocator/fs/cos/COSAPIClient.java#L304). 

However the code in the master branch (which I believe is the code published to maven) is different and seems to require an access key as seen [here](https://github.com/CODAIT/stocator/blob/master/src/main/java/com/ibm/stocator/fs/cos/COSAPIClient.java#L275).

Can you verify that the documentation is correct and I should only need to supply the iam.api.key.

**Comment by gilv** [comment]
@IainMeeke the master branch is based on Amazon SDK, while cos-sdk branch is based on IBM COS SDK. In the near future we will change that, so master branch will use cos-sdk.
Because of this, you can use HMAC authentication (access key + secret key ) when you use master branch and you have an option to use iam key only for cos-sdk branch.
Maven repository is based on master.

Does this helps?

**Comment by IainMeeke** [comment]
Yes this explains the issues I was having, thank you for the response. It could be worth adding this difference to the documentation to avoid further confusion.
