### ISSUE TITLE
Bug - Spark Dynamic Partition Insert not supported by Stocator

### ISSUE THREAD

**Issue by yangchenghuang** [CODAIT/stocator#256]
Hey @gilv 

We (Truata) are using Stocator with IBM IAE to access IBM CoS. We recently found the following issue with Stocator when running Spark Dynamic Partition Insert (added to Spark since Spark 2.3.0) -
https://issues.apache.org/jira/browse/SPARK-20236
https://docs.databricks.com/spark/latest/spark-sql/language-manual/insert.html

When we try to run "INSERT OVERWRITE TABLE emp2 PARTITION (dept_id) ...", the data partitions are not inserted / overwritten. Instead, the partitions are wiped off. Please refer to the attached files to re-produce this issue -

[cos-insert-overwrite.txt](https://github.com/CODAIT/stocator/files/5063487/cos-insert-overwrite.txt)
[emp.txt](https://github.com/CODAIT/stocator/files/5063488/emp.txt)

We found a potential bug with the rename function of COSAPIClient.java. Existing rename function assumes srcPath has to be a "file" object. When running Spark Dynamic Partition Insert, the srcPath passed in is actually a "directory" object (e.g. partitions), which  is not supported by rename and generates an error "rename: renaming file {} to {} failed. Source file is directory".

Could you please share your thoughts on this issue? 

We already created a patch for this and tested in our system. We can create a pull request and commit the changes after this is confirmed.

Thanks/Yangcheng

**Comment by gilv** [comment]
@yangchenghuang Thanks for reporting this. My general view that insert dynamic partitions against any object storage is a bad idea for Spark ( or Hive). The process involves a lot of listing, renames on directory level, tmp files, object renames, etc. Since rename is not atomic operation in object storage, this process may generate corrupted data or partial data. Directory rename is even worse. In addition, there are a lot requests, so if there are many data - it can be very slow and usually will fail. This is true for any connector, not particular Stocator issue. 
In general, rename on directory level is a very bad approach for object storage and it's a known issue, documented by many. We can of course support this in Stocator and your pull request will be great to have - but you should still try to avoid overwrite dynamic partitions against object storage - as directory rename may introduce other issues.

**Comment by yangchenghuang** [comment]
@gilv Many thanks for the prompt response!
I totally agree with your concerns on rename and (in general) directory-level operations with object storage. We are indeed observing very heavy requests (status check, IAM auth etc), even without rename on partitions / directories.
Thanks for the suggestions. We are working on repartitioning the data, to avoid having too many files under a partition. It would still be great for Stocator to support this Spark feature (dynamic partition insert). It is up to the developers to be fully aware of the cost when using this in their solutions. :)
I will go ahead and create the pull request. And will keep you updated!

**Comment by mrmadira** [comment]
Hi @yangchenghuang - you mentioned you have tested this on your system. Can you give details of how you tested? Was it using spark-shell or spark-submit?
